project:
  type: website
  output-dir: .
  resources:
    - images

website:
  title: ""
  navbar:
    pinned: true
    background: primary
    search: true
    page-navigation: true
    left:
      - icon: house
        text: "Home"
        href: index.qmd

      - icon: microscope
        text: "Research"
        href: "#research-teaching-areas"

      - icon: book-open
        text: "Publications"
        href: "#publications-open-repositories"

      - icon: flask
        text: "Projects"
        href: "#projects"

      - icon: id-badge
        text: "Profiles"
        href: "#professional-profiles"

  page-footer:
    background: "#0d2a54"
    foreground: "#ffffff"
    left: "© 2025 Jesús Cáceres-Tello"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    css: styles.css
    smooth-scroll: true



