project:
  type: website
  output-dir: .
  resources:
    - images

website:
  navbar:
    logo: ""
    pinned: true
    background: primary
    search: true
    page-navigation: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: "#research-teaching-areas"
      - text: "Publications"
        href: "#publications-open-repositories"
      - text: "Projects"
        href: "#projects"
      - text: "Contact"
        href: "#connect"
  page-footer:
    background: "#0d2a54"
    foreground: "#ffffff"
    left: "© 2025 Jesús Cáceres-Tello"

format:
  html:
    theme: cosmo
    css: styles.css



